CREATE TABLE `audit_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`leadId` int NOT NULL,
	`campaignId` int NOT NULL,
	`scoreSeo` int NOT NULL DEFAULT 0,
	`scoreSpeed` int NOT NULL DEFAULT 0,
	`scoreContact` int NOT NULL DEFAULT 0,
	`scoreSocial` int NOT NULL DEFAULT 0,
	`scoreTotal` int NOT NULL DEFAULT 0,
	`priority` enum('high','medium','low') NOT NULL DEFAULT 'low',
	`temperature` enum('hot','warm','cold') NOT NULL DEFAULT 'cold',
	`detectedIssues` json NOT NULL DEFAULT ('[]'),
	`recommendedAction` text,
	`pagespeedScore` int,
	`loadTimeMs` int,
	`hasMeta` boolean DEFAULT false,
	`hasH1` boolean DEFAULT false,
	`hasSitemap` boolean DEFAULT false,
	`hasHttps` boolean DEFAULT false,
	`isMobileFriendly` boolean DEFAULT false,
	`emailsFound` json NOT NULL DEFAULT ('[]'),
	`phonesFound` json NOT NULL DEFAULT ('[]'),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `audit_results_id` PRIMARY KEY(`id`),
	CONSTRAINT `audit_results_leadId_unique` UNIQUE(`leadId`)
);
--> statement-breakpoint
CREATE TABLE `campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`businessType` varchar(255) NOT NULL,
	`city` varchar(255) NOT NULL,
	`zones` json NOT NULL DEFAULT ('[]'),
	`sectors` json NOT NULL DEFAULT ('[]'),
	`searchRadius` int NOT NULL DEFAULT 5000,
	`minRating` decimal(3,1) NOT NULL DEFAULT '4.0',
	`minReviews` int NOT NULL DEFAULT 75,
	`maxPages` int NOT NULL DEFAULT 1,
	`onlyWithoutWebsite` boolean NOT NULL DEFAULT false,
	`checkWebsiteStatus` boolean NOT NULL DEFAULT false,
	`enableWebsiteAudit` boolean NOT NULL DEFAULT true,
	`enablePagespeed` boolean NOT NULL DEFAULT false,
	`enableEmailExtraction` boolean NOT NULL DEFAULT true,
	`enableSocialExtraction` boolean NOT NULL DEFAULT true,
	`maxAuditLeads` int NOT NULL DEFAULT 100,
	`status` enum('pending','running','completed','error') NOT NULL DEFAULT 'pending',
	`progress` int NOT NULL DEFAULT 0,
	`currentStep` varchar(255),
	`totalLeads` int NOT NULL DEFAULT 0,
	`auditedLeads` int NOT NULL DEFAULT 0,
	`logs` json NOT NULL DEFAULT ('[]'),
	`outputExcelKey` varchar(500),
	`outputCsvKey` varchar(500),
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`completedAt` timestamp,
	CONSTRAINT `campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaignId` int NOT NULL,
	`businessName` varchar(255) NOT NULL,
	`sector` varchar(255),
	`zone` varchar(255),
	`address` text,
	`phone` varchar(64),
	`website` varchar(500),
	`email` varchar(320),
	`rating` decimal(3,1),
	`reviewCount` int DEFAULT 0,
	`hasWebsite` boolean DEFAULT false,
	`websiteStatus` varchar(64),
	`facebook` varchar(500),
	`instagram` varchar(500),
	`linkedin` varchar(500),
	`twitter` varchar(500),
	`googlePlaceId` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_settings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`googlePlacesApiKey` varchar(500),
	`pagespeedApiKey` varchar(500),
	`hunterApiKey` varchar(500),
	`defaultMinRating` decimal(3,1) DEFAULT '4.0',
	`defaultMinReviews` int DEFAULT 75,
	`defaultMaxPages` int DEFAULT 1,
	`defaultMaxAuditLeads` int DEFAULT 100,
	`defaultEnableWebsiteAudit` boolean DEFAULT true,
	`defaultEnableEmailExtraction` boolean DEFAULT true,
	`defaultEnableSocialExtraction` boolean DEFAULT true,
	`ownerName` varchar(255),
	`ownerEmail` varchar(320),
	`agencyName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_settings_id` PRIMARY KEY(`id`),
	CONSTRAINT `user_settings_userId_unique` UNIQUE(`userId`)
);
