/**
 * Python Importer — Imports results from Python pipeline output files
 * Reads JSON files generated by Python scripts and imports them into the database
 */

import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { createLeads, createAuditResults } from "./db";

interface PythonLead {
  place_id: string;
  name: string;
  sector?: string;
  zone?: string;
  address?: string;
  website?: string | null;
  email?: string | null;
  phone?: string;
  rating?: number | string;
  review_count?: number;
  facebook?: string | null;
  instagram?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  score_seo: number;
  score_speed: number;
  score_contact: number;
  score_social: number;
  score_total: number;
  priority: "high" | "medium" | "low";
  temperature: "hot" | "warm" | "cold";
  detected_issues: string[];
  recommended_action: string;
  pagespeed_score?: number | null;
  load_time_ms?: number | null;
  has_meta?: boolean;
  has_h1?: boolean;
  has_sitemap?: boolean;
  has_https?: boolean;
  is_mobile_friendly?: boolean;
  emails_found?: string[];
  phones_found?: string[];
  [key: string]: unknown;
}

interface FinalLeadsOutput {
  timestamp: string;
  total_leads: number;
  leads: PythonLead[];
}

/**
 * Imports results from python_pipeline/output/final_leads.json
 * Creates leads and audit_results records in the database
 * Throws error if output file is missing or invalid
 */
export async function importResultsFromPythonOutput(
  campaignId: number,
  pythonCwd: string = join(process.cwd(), "python_pipeline")
): Promise<{ leadsCreated: number; auditsCreated: number }> {
  const outputFile = join(pythonCwd, "output", "final_leads.json");

  if (!existsSync(outputFile)) {
    throw new Error(`Output file not found: ${outputFile}`);
  }

  // Read and parse the JSON file
  let data: FinalLeadsOutput;
  try {
    const fileContent = readFileSync(outputFile, "utf-8");
    data = JSON.parse(fileContent);
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    throw new Error(`Failed to parse output file: ${msg}`);
  }

  if (!data.leads || !Array.isArray(data.leads)) {
    throw new Error("Invalid output format: missing 'leads' array");
  }

  if (data.leads.length === 0) {
    console.log(`[pythonImporter] No leads found in output file`);
    return { leadsCreated: 0, auditsCreated: 0 };
  }

  console.log(`[pythonImporter] Importing ${data.leads.length} leads from ${outputFile}`);

  // Validate required fields in each lead
  for (let i = 0; i < data.leads.length; i++) {
    const lead = data.leads[i];
    if (!lead.place_id || !lead.name) {
      throw new Error(
        `Lead at index ${i} missing required fields: place_id or name`
      );
    }
    if (
      typeof lead.score_seo !== "number" ||
      typeof lead.score_speed !== "number" ||
      typeof lead.score_contact !== "number" ||
      typeof lead.score_social !== "number" ||
      typeof lead.score_total !== "number"
    ) {
      throw new Error(`Lead at index ${i} missing or invalid score fields`);
    }
  }

  // Transform Python leads to database format
  const leadsToCreate = data.leads.map((lead) => ({
    campaignId,
    businessName: lead.name,
    sector: lead.sector || "Unknown",
    zone: lead.zone || "Unknown",
    address: lead.address || "",
    phone: lead.phone || null,
    website: lead.website || null,
    email: lead.email || null,
    rating: String(lead.rating || "0"),
    reviewCount: Number(lead.review_count || 0),
    hasWebsite: !!lead.website,
    websiteStatus: lead.website ? "ok" : "none",
    facebook: lead.facebook || null,
    instagram: lead.instagram || null,
    linkedin: lead.linkedin || null,
    twitter: lead.twitter || null,
    googlePlaceId: lead.place_id,
  }));

  // Create leads
  await createLeads(leadsToCreate);
  console.log(`[pythonImporter] Created ${leadsToCreate.length} leads`);

  // Get the created leads to get their IDs
  const { getLeadsByCampaign } = await import("./db");
  const createdLeads = await getLeadsByCampaign(campaignId);

  if (createdLeads.length === 0) {
    throw new Error("No leads were created in database");
  }

  if (createdLeads.length !== data.leads.length) {
    console.warn(
      `[pythonImporter] Warning: Created ${createdLeads.length} leads but expected ${data.leads.length}`
    );
  }

  // Transform Python audit results to database format
  const auditsToCreate = data.leads.map((lead, index) => {
    const createdLead = createdLeads[index];
    if (!createdLead) {
      throw new Error(
        `Lead at index ${index} not found in database after creation`
      );
    }
    return {
      leadId: createdLead.id,
      campaignId,
      scoreSeo: lead.score_seo,
      scoreSpeed: lead.score_speed,
      scoreContact: lead.score_contact,
      scoreSocial: lead.score_social,
      scoreTotal: lead.score_total,
      priority: lead.priority,
      temperature: lead.temperature,
      detectedIssues: lead.detected_issues || [],
      recommendedAction: lead.recommended_action || "",
      pagespeedScore: lead.pagespeed_score || null,
      loadTimeMs: lead.load_time_ms || null,
      hasMeta: lead.has_meta || false,
      hasH1: lead.has_h1 || false,
      hasSitemap: lead.has_sitemap || false,
      hasHttps: lead.has_https || false,
      isMobileFriendly: lead.is_mobile_friendly || false,
      emailsFound: lead.emails_found || (lead.email ? [lead.email] : []),
      phonesFound: lead.phones_found || (lead.phone ? [lead.phone] : []),
    };
  });

  // Create audit results
  await createAuditResults(auditsToCreate);
  console.log(`[pythonImporter] Created ${auditsToCreate.length} audit results`);

  return {
    leadsCreated: createdLeads.length,
    auditsCreated: auditsToCreate.length,
  };
}
